import React from 'react';
import LegalContainer from '../../components/legal/LegalContainer';

const AIGovernance: React.FC = () => {
  return (
    <LegalContainer title="Responsible AI Governance" icon="ai">
      <section>
        <p className="lead">
          Neural OS is built on the principle that AI should serve as an intellectual augment, not a replacement. Our governance framework is designed around enterprise-grade principles and is inspired by global standards such as ISO 9001 and CMMI process maturity models.
        </p>
      </section>

      <hr className="border-white/5" />

      <section className="space-y-4">
        <h3 className="text-xl font-semibold text-white tracking-tight">1. Ethical AI Principles</h3>
        <p>
          We adhere to a set of core ethical standards to ensure the responsible deployment of our cognition layers:
        </p>
      <ul className="space-y-2 list-disc pl-5">
          <li><strong className="text-theme-primary">Transparency:</strong> Clearly identifying when content or logic is generated by the AI engine.</li>
          <li><strong className="text-theme-primary">Accountability:</strong> Maintaining human oversight (the "Architect") over all automated system decisions.</li>
          <li><strong className="text-theme-primary">Fairness:</strong> Actively monitoring for and mitigating biases within our prompt engineering and model selection.</li>
        </ul>
      </section>

      <hr className="border-white/5" />

      <section className="space-y-4">
        <h3 className="text-xl font-semibold text-white tracking-tight">2. Responsible Usage & Safety</h3>
        <p>
          The Neural OS interface includes active prompt safety layers to prevent the generation of harmful, unethical, or deceptive content. We align our prompt architecture with secure AI lifecycle standards to ensure the integrity of the distributed cognition ecosystem.
        </p>
      </section>

      <hr className="border-white/5" />

      <section className="space-y-4">
        <h3 className="text-xl font-semibold text-white tracking-tight">3. Data Minimization & Privacy</h3>
        <p>
          Our RAG (Retrieval-Augmented Generation) and data governance architecture are designed to minimize data exposure. Only the necessary context is provided to the AI engine to fulfill user directives, ensuring a "Privacy by Design" approach.
        </p>
      </section>

      <hr className="border-white/5" />

      <section className="space-y-4">
        <h3 className="text-xl font-semibold text-white tracking-tight">4. Model Limitations & Human-in-the-Loop</h3>
        <p>
          We acknowledge the inherent limitations of large language models. Neural OS operates on a "Human-in-the-Loop" philosophy, where the AI provides architectural possibilities and the user (the Architect) provides the final validation and directive.
        </p>
      </section>

      <hr className="border-white/5" />

      <section className="space-y-4">
        <h3 className="text-xl font-semibold text-white tracking-tight">5. Compliance & Security</h3>
        <p>
          While we are an independent platform, our AI operations are designed to be consistent with enterprise-grade security protocols. We utilize hardened API endpoints and secure orchestration layers to manage the flow of data between the user and the cognition engine.
        </p>
      </section>

      <hr className="border-white/5" />

      <section className="space-y-4">
        <h3 className="text-xl font-semibold text-white tracking-tight">6. Continuous Improvement</h3>
        <p>
          Aligned with CMMI maturity concepts, we continuously iterate on our AI governance processes. We regularly audit our neural link stability and cognition accuracy to ensure we maintain the highest standards of digital architecture.
        </p>
      </section>
    </LegalContainer>
  );
};

export default AIGovernance;
