import React from 'react';
import LegalContainer from '../../components/legal/LegalContainer';

const Terms: React.FC = () => {
  return (
    <LegalContainer title="Terms of Service" icon="terms">
      <section className="space-y-4">
        <h3 className="text-xl font-semibold text-white tracking-tight">1. Platform Usage</h3>
        <p>
          Welcome to Neural OS. By accessing or using our distributed cognition ecosystem, you agree to comply with and be bound by these Terms of Service. This platform is designed for professional architectural visualization and AI-driven system orchestration.
        </p>
      </section>

      <hr className="border-white/5" />

      <section className="space-y-4">
        <h3 className="text-xl font-semibold text-white tracking-tight">2. User Responsibilities</h3>
        <p>
          As an Architect within our ecosystem, you are responsible for maintaining the security of your neural link (account). Any activity performed through your credentials is deemed your responsibility. You agree not to engage in reverse engineering, unauthorized data extraction, or any activity that compromises the integrity of the Neural OS grid.
        </p>
      </section>

      <hr className="border-white/5" />

      <section className="space-y-4">
        <h3 className="text-xl font-semibold text-white tracking-tight">3. AI-Generated Content Disclaimer</h3>
        <p>
          Neural OS utilizes advanced generative models (including Gemini API) to assist in platform interactions. <strong>Content generated by the AI is provided "as-is"</strong>. While we strive for architectural precision, Neural OS does not guarantee the factual accuracy or suitability of AI-generated outputs for critical decision-making. Users must exercise professional judgment.
        </p>
      </section>

      <hr className="border-white/5" />

      <section className="space-y-4">
        <h3 className="text-xl font-semibold text-white tracking-tight">4. Intellectual Property</h3>
        <p>
          The underlying architecture, "Neural OS" branding, and liquid interface designs are the exclusive property of Vivek Sharma and his associated entities. Users retain rights to their personal data, but grant Neural OS a non-exclusive license to process such data for the purpose of service delivery and platform optimization.
        </p>
      </section>

      <hr className="border-white/5" />

      <section className="space-y-4">
        <h3 className="text-xl font-semibold text-white tracking-tight">5. Limitation of Liability</h3>
        <p>
          To the maximum extent permitted by law, Neural OS and its architect shall not be liable for any indirect, incidental, or consequential damages arising out of your use of the platform. This includes, but is not limited to, data loss, neural link interruptions, or discrepancies in AI-driven projections.
        </p>
      </section>

      <hr className="border-white/5" />

      <section className="space-y-4">
        <h3 className="text-xl font-semibold text-white tracking-tight">6. Termination Policy</h3>
        <p>
          We reserve the right to suspend or terminate access to the Neural OS gateway at our discretion, particularly in cases of usage policy violations or attempts to destabilize the cognition layer.
        </p>
      </section>

      <hr className="border-white/5" />

      <section className="space-y-4">
        <h3 className="text-xl font-semibold text-white tracking-tight">7. Governing Law</h3>
        <p>
          These terms are governed by the principles of distributed digital governance and applicable jurisdictional laws. Any disputes shall be resolved through professional arbitration.
        </p>
      </section>
    </LegalContainer>
  );
};

export default Terms;
